name: Notify Discord

on:
  workflow_run:
    workflows: ["Send message"]
    types:
      - completed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification to Discord
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          # Dynamic message content based on the last commit message
          message: "Commit ${{ github.event.workflow_run.head_commit.message }}"
          # Custom username for the Discord message
          username: "Github"
          # Custom avatar URL for the Discord message
          avatar: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

