name: Send Message on Issue Open

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const issueNumber = context.issue.number;
            const message = `Thank you for opening issue #${issueNumber} We appreciate your contribution.`;

            await github.rest.issues.createComment({
              issue_number: issueNumber,
              owner: owner,
              repo: repo,
              body: message
            });
