name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Replace line 20 in README.md
        run: |
          echo '<img src="https://img.shields.io/badge/Tested-no-black?logo=linux">' >> README.md
          
      - name: Commit and Push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add README.md
          git commit -m "📝 Rename yes to no"
          git push