name: Start ssh

on: [push] # Specify when this workflow should run, e.g., on push events

jobs:
  start_ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start SSH
        uses: Tofandel/ssh-server-action@v1.0.0
        with:
          hostname: "SSH Server" # Optional, the display hostname of the server
          port: 2222 # Optional, default value is 22. The exposed ssh port
          user_name: "root" # Optional, default value is ssh-user
          user_password: ${{ secrets.PASSWORD }} # Optional, use GitHub Secrets for security
          sudo_access: true # Optional, allow user to use sudo without password, default: false
