on:
    schedule: [{cron: "*/7 * * * *"}]
    workflow_dispatch:
    push: {branches: ["master", "main"]}
  
jobs:
    status:
      runs-on: ubuntu-latest
      name: Update Discord Status
      steps:
        - name: Checkout files
          uses: actions/checkout@v3
        - name: Update Status
          uses: CompeyDev/discord-status-action@0.2.4
          with:
            file: README.md
            id: "1125429179685548112" # Replace with your Discord User ID.
        - name: Commit and push if there are changes
          run: |-
            git diff
            git config --global user.email "artin962354@proton.me" # Replace with an email associated to your GitHub Account.
            git config --global user.name "Artin Karimi"
            git diff --quiet || (git add -u && git commit -m "🚀 Update Discord Status")
            git push               