# Setup Web Terminal CLI only
name: CI

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Web Terminal
        uses: zmicro-design/action-setup-web-terminal@v1